# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Grocery Bazaar' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod "AFNetworking", "2.5.0"
  pod 'TPKeyboardAvoiding', '~> 1.3'

  pod 'SWRevealViewController', '~> 2.3'

  # Pods for Grocery Bazaar

#hey

end
